---
- name: Setup Apache and configure Nginx as reverse proxy
  hosts: web
  become: yes
  serial: 1
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Configure Nginx as reverse proxy
      copy:
        dest: /etc/nginx/sites-available/reverse_proxy
        content: |
          server {
              listen 80;
              server_name devopstitans.opstree.com;

              location / {
                  proxy_pass http://localhost:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }
      notify: Reload Nginx

    - name: Enable reverse proxy config
      file:
        src: /etc/nginx/sites-available/reverse_proxy
        dest: /etc/nginx/sites-enabled/reverse_proxy
        state: link
        force: yes

    - name: Remove default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
