---
- name: Setup team member websites and schedule rotation
  hosts: web
  become: yes
  serial: 1
  vars:
    websites:
      - name: Rehan
        content: "Welcome to Rehan's Page!"
      - name: Harsh
        content: "This is Harsh's Website"
      - name: Prakash
        content: "Prakash's Portal is live"

  tasks:
    - name: Create website directories
      file:
        path: "/var/www/{{ item.name }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      loop: "{{ websites }}"

    - name: Create index.html for each member
      copy:
        dest: "/var/www/{{ item.name }}/index.html"
        content: "{{ item.content }}"
        owner: www-data
        group: www-data
        mode: '0644'
      loop: "{{ websites }}"

    - name: Copy website rotation script
      copy:
        src: files/rotate_site.sh
        dest: /usr/local/bin/rotate_site.sh
        mode: '0755'

    - name: Add cron job to rotate website every 2 hours
      cron:
        name: "Rotate website every 2 hours"
        job: "/usr/local/bin/rotate_site.sh"
        minute: "0"
        hour: "*/2"

