- name: Ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: yes

- name: Create apt keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes GPG key (v1.29)
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor | tee /etc/apt/keyrings/kubernetes-apt-keyring.gpg > /dev/null
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true

- name: Add Kubernetes apt repository (v1.29)
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    filename: kubernetes
    state: present

- name: Update apt cache (force refresh)
  apt:
    update_cache: yes

- name: Install Kubernetes components (v1.29)
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest

- name: Enable and start kubelet
  service:
    name: kubelet
    enabled: true
    state: started

- name: Deploy kube config using template
  template:
    src: kube_config.j2
    dest: /etc/kubernetes/config.yaml
  notify: Restart kubelet


